/*
Cubesat Space Protocol - A small network-layer protocol designed for Cubesats
Copyright (C) 2012 GomSpace ApS (http://www.gomspace.com)
Copyright (C) 2012 AAUSAT3 Project (http://aausat3.space.aau.dk)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/

//! # libcsp — Safe Rust bindings for libcsp v1.6
//!
//! This crate provides idiomatic, zero-unsafe Rust wrappers around the
//! [Cubesat Space Protocol](https://github.com/libcsp/libcsp) C library.
//!
//! ## Important Limitation
//!
//! **Only one [`CspNode`] can exist at a time** in a process, due to global state
//! in the underlying libcsp C library. Attempting to call [`CspConfig::init()`]
//! twice will return [`CspError::AlreadyInitialized`].
//!
//! You can [`Clone`] a `CspNode` to share it across threads, but you cannot have
//! two independent CSP stacks.
//!
//! ## Quick start
//!
//! ```no_run
//! use libcsp::{CspConfig, Packet, Socket};
//!
//! // Initialise the CSP stack
//! let node = CspConfig::new()
//!     .address(1)
//!     .hostname("my-sat")
//!     .buffers(10, 256)
//!     .init()
//!     .expect("csp_init failed");
//!
//! // Start the router task (POSIX: spawns a pthread)
//! node.route_start_task(4096, 0).expect("router task failed");
//!
//! // Server: bind port 10
//! let sock = Socket::new(0).expect("csp_socket failed");
//! sock.bind(10).unwrap();
//! sock.listen(5).unwrap();
//!
//! if let Some(conn) = sock.accept(1000) {
//!     while let Some(pkt) = conn.read(100) {
//!         // pkt is freed automatically on drop
//!         let _ = pkt.data();
//!     }
//! }
//!
//! // Client: connect and send
//! if let Some(conn) = node.connect(libcsp::Priority::Norm, 2, 10, 1000, 0) {
//!     let mut pkt = Packet::get(32).expect("no packet buffers");
//!     pkt.write(b"hello").unwrap();
//!     let _ = conn.send_discard(pkt, 100);
//! }
//! ```
//!
//! ## Feature flags
//!
//! | Feature | Default | Description |
//! |---------|---------|-------------|
//! | `std` | ✓ | Enable `std::error::Error` impl and standard library helpers |
//! | `rdp` | ✓ | Reliable Datagram Protocol transport |
//! | `crc32` | ✓ | CRC32 packet integrity |
//! | `hmac` | ✓ | HMAC-SHA1 authentication |
//! | `xtea` | ✓ | XTEA encryption |
//! | `qos` | ✓ | Quality of Service (priority queues) |
//! | `promisc` | ✓ | Promiscuous mode |
//! | `dedup` | ✓ | Packet deduplication |
//! | `cidr-rtable` | – | CIDR routing table (instead of static) |
//! | `socketcan` | – | Linux SocketCAN driver |
//! | `zmq` | – | ZMQ hub interface |
//! | `usart-linux` | – | Linux USART/KISS driver |
//! | `usart-windows` | – | Windows USART driver |
//! | `debug` | – | Enable CSP debug output |
//! | `debug-timestamp` | – | Add timestamps to debug output |
//!
//! ## `no_std` support
//!
//! Disable the `std` feature to build for `no_std` targets.  The `alloc` crate
//! is still required (for `CString` in [`CspConfig`]).  All other modules use
//! only `core`.
//!
//! ```toml
//! [dependencies]
//! libcsp = { version = "1.6", default-features = false, features = ["rdp", "crc32"] }
//! ```

// ── no_std configuration ─────────────────────────────────────────────────────
#![cfg_attr(not(feature = "std"), no_std)]

// We need `alloc` for CString in init.rs on no_std targets.
extern crate alloc;

// ── Modules ───────────────────────────────────────────────────────────────────

/// Raw, unsafe FFI bindings generated by bindgen.
///
/// Prefer the safe wrappers in the crate root.  The raw API is available here
/// for advanced use cases (e.g. custom interfaces, direct `csp_rtable_*` calls).
pub mod sys;

pub mod arch;
mod connection;
mod error;
mod init;
pub mod interface;
mod packet;
pub mod promisc;
pub mod route;
pub mod service;
mod socket;

#[cfg(feature = "debug")]
pub mod debug;

// When 'external-arch' is enabled, libcsp expects the user to provide the
// architecture-specific implementation. To allow standard host tests and
// examples to run with this feature enabled (e.g. via --all-features),
// we provide a default stub implementation for host platforms.
#[cfg(all(
    feature = "std",
    feature = "external-arch",
    any(target_os = "linux", target_os = "macos", target_os = "windows")
))]
mod arch_default_export {
    use crate::arch::test_arch::{TestArch, ARCH};
    crate::export_arch!(TestArch, ARCH);
}

// ── Public re-exports ─────────────────────────────────────────────────────────

pub use arch::CspArch;
pub use connection::Connection;
pub use error::CspError;
pub use init::{CspConfig, CspNode};
pub use interface::{CspInterface, InterfaceHandle};
pub use packet::Packet;
pub use service::{Dispatcher, Ident, IfStats};
pub use socket::Socket;

#[macro_use]
pub mod arch_macro {
    pub use crate::export_arch;
}

/// Convenience `Result` type with [`CspError`] as the error variant.
pub type Result<T> = core::result::Result<T, CspError>;

// ── Priority enum ─────────────────────────────────────────────────────────────

/// CSP message priority.
///
/// Matches `csp_prio_t` in `csp_types.h`.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Priority {
    /// Critical priority (0 — highest).
    Critical = sys::csp_prio_t_CSP_PRIO_CRITICAL as u8,
    /// High priority (1).
    High = sys::csp_prio_t_CSP_PRIO_HIGH as u8,
    /// Normal priority (2 — default).
    Norm = sys::csp_prio_t_CSP_PRIO_NORM as u8,
    /// Low priority (3 — lowest).
    Low = sys::csp_prio_t_CSP_PRIO_LOW as u8,
}

// ── Socket / connection option constants ──────────────────────────────────────

/// Socket options bitmask (`CSP_SO_*`).
///
/// These map directly to the `CSP_SO_*` constants in `csp_types.h` and can be
/// combined with `|`.
pub mod socket_opts {
    use crate::sys;

    /// No options.
    pub const NONE: u32 = sys::CSP_SO_NONE;
    /// Require RDP.
    pub const RDP_REQ: u32 = sys::CSP_SO_RDPREQ;
    /// Prohibit RDP.
    pub const RDP_PROHIB: u32 = sys::CSP_SO_RDPPROHIB;
    /// Require HMAC.
    pub const HMAC_REQ: u32 = sys::CSP_SO_HMACREQ;
    /// Prohibit HMAC.
    pub const HMAC_PROHIB: u32 = sys::CSP_SO_HMACPROHIB;
    /// Require XTEA.
    pub const XTEA_REQ: u32 = sys::CSP_SO_XTEAREQ;
    /// Prohibit XTEA.
    pub const XTEA_PROHIB: u32 = sys::CSP_SO_XTEAPROHIB;
    /// Require CRC32.
    pub const CRC32_REQ: u32 = sys::CSP_SO_CRC32REQ;
    /// Prohibit CRC32.
    pub const CRC32_PROHIB: u32 = sys::CSP_SO_CRC32PROHIB;
    /// Enable connection-less mode.
    pub const CONN_LESS: u32 = sys::CSP_SO_CONN_LESS;
}

/// Connection options aliases (`CSP_O_*`).
///
/// Same numeric values as [`socket_opts`] — provided as a separate module
/// for clarity at call sites.
pub mod conn_opts {
    pub use super::socket_opts::{
        CRC32_PROHIB as NOCRC32, CRC32_REQ as CRC32, HMAC_PROHIB as NOHMAC, HMAC_REQ as HMAC, NONE,
        RDP_PROHIB as NORDP, RDP_REQ as RDP, XTEA_PROHIB as NOXTEA, XTEA_REQ as XTEA,
    };
}

/// Broadcast address (all nodes).
pub const BROADCAST_ADDR: u32 = sys::CSP_ID_HOST_MAX; // CSP_ID_HOST_MAX = (1 << 5) - 1

/// Accept packets on any port (use with [`Socket::bind`]).
pub const ANY_PORT: u8 = sys::CSP_ANY as u8; // CSP_ANY

/// Infinite timeout (block until event occurs).
pub const MAX_TIMEOUT: u32 = u32::MAX;

// ── Port enum ─────────────────────────────────────────────────────────────────

/// CSP port numbers.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Port {
    /// CSP Management Protocol (0).
    Cmp = sys::csp_service_port_t_CSP_CMP as u8,
    /// Ping / echo (1).
    Ping = sys::csp_service_port_t_CSP_PING as u8,
    /// Process list (2).
    Ps = sys::csp_service_port_t_CSP_PS as u8,
    /// Free memory query (3).
    MemFree = sys::csp_service_port_t_CSP_MEMFREE as u8,
    /// Reboot / shutdown (4).
    Reboot = sys::csp_service_port_t_CSP_REBOOT as u8,
    /// Free buffer count (5).
    BufFree = sys::csp_service_port_t_CSP_BUF_FREE as u8,
    /// Uptime query (6).
    Uptime = sys::csp_service_port_t_CSP_UPTIME as u8,
    /// Accept packets on any port (255).
    Any = sys::CSP_ANY as u8,
    /// Custom user-defined port.
    Custom(u8) = 254,
}

impl From<u8> for Port {
    fn from(p: u8) -> Self {
        match p {
            0 => Port::Cmp,
            1 => Port::Ping,
            2 => Port::Ps,
            3 => Port::MemFree,
            4 => Port::Reboot,
            5 => Port::BufFree,
            6 => Port::Uptime,
            255 => Port::Any,
            p => Port::Custom(p),
        }
    }
}

impl From<Port> for u8 {
    fn from(p: Port) -> u8 {
        match p {
            Port::Cmp => 0,
            Port::Ping => 1,
            Port::Ps => 2,
            Port::MemFree => 3,
            Port::Reboot => 4,
            Port::BufFree => 5,
            Port::Uptime => 6,
            Port::Any => 255,
            Port::Custom(p) => p,
        }
    }
}

impl Port {
    /// Return true if this is a reserved libcsp service port (0-6).
    pub fn is_service_port(&self) -> bool {
        let p: u8 = (*self).into();
        p <= 6
    }
}

// ── Standard ports ────────────────────────────────────────────────────────────

/// Reserved CSP service port numbers (`csp_service_port_t`).
pub mod ports {
    use crate::sys;

    /// CSP Management Protocol.
    pub const CMP: u32 = sys::csp_service_port_t_CSP_CMP;
    /// Ping / echo.
    pub const PING: u32 = sys::csp_service_port_t_CSP_PING;
    /// Process list.
    pub const PS: u32 = sys::csp_service_port_t_CSP_PS;
    /// Free memory query.
    pub const MEMFREE: u32 = sys::csp_service_port_t_CSP_MEMFREE;
    /// Reboot / shutdown.
    pub const REBOOT: u32 = sys::csp_service_port_t_CSP_REBOOT;
    /// Free buffer count.
    pub const BUF_FREE: u32 = sys::csp_service_port_t_CSP_BUF_FREE;
    /// Uptime query.
    pub const UPTIME: u32 = sys::csp_service_port_t_CSP_UPTIME;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_port_mapping() {
        assert_eq!(u8::from(Port::Cmp), 0);
        assert_eq!(u8::from(Port::Ping), 1);
        assert_eq!(u8::from(Port::Any), 255);
        assert_eq!(u8::from(Port::Custom(10)), 10);

        assert_eq!(Port::from(0), Port::Cmp);
        assert_eq!(Port::from(1), Port::Ping);
        assert_eq!(Port::from(255), Port::Any);
        assert_eq!(Port::from(10), Port::Custom(10));
    }
}

// ── Test helpers ──────────────────────────────────────────────────────────────

#[cfg(test)]
pub(crate) mod test_helpers {
    use crate::CspConfig;
    use std::sync::Mutex;

    /// Global test lock to serialize CSP initialization across all tests.
    /// Since libcsp only allows one node at a time, tests must run sequentially.
    pub static TEST_LOCK: Mutex<()> = Mutex::new(());

    /// Helper to run a test with CSP initialized.
    /// Automatically serializes test execution and cleans up after the test.
    pub fn with_csp_node<F: FnOnce(&crate::CspNode)>(f: F) {
        // Lock the mutex - DO NOT ignore poison panics as they indicate test failures
        let _guard = TEST_LOCK.lock().unwrap();

        // Initialize CSP for this test
        let node = CspConfig::new()
            .address(1)
            .buffers(10, 256)
            .init()
            .expect("failed to init CSP for tests");

        // Run the test with the node
        f(&node);

        // Node is dropped here, calling csp_free_resources
    }
}
