/*
Cubesat Space Protocol - A small network-layer protocol designed for Cubesats
Copyright (C) 2012 GomSpace ApS (http://www.gomspace.com)
Copyright (C) 2012 AAUSAT3 Project (http://aausat3.space.aau.dk)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/

//! # libcsp — Safe Rust bindings for libcsp v1.6
//!
//! This crate provides idiomatic, zero-unsafe Rust wrappers around the
//! [Cubesat Space Protocol](https://github.com/libcsp/libcsp) C library.
//!
//! ## Quick start
//!
//! ```no_run
//! use libcsp::{CspConfig, Packet, Socket};
//!
//! // Initialise the CSP stack
//! let node = CspConfig::new()
//!     .address(1)
//!     .hostname("my-sat")
//!     .buffers(10, 256)
//!     .init()
//!     .expect("csp_init failed");
//!
//! // Start the router task (POSIX: spawns a pthread)
//! node.route_start_task(4096, 0).expect("router task failed");
//!
//! // Server: bind port 10
//! let sock = Socket::new(0).expect("csp_socket failed");
//! sock.bind(10).unwrap();
//! sock.listen(5).unwrap();
//!
//! if let Some(conn) = sock.accept(1000) {
//!     while let Some(pkt) = conn.read(100) {
//!         // pkt is freed automatically on drop
//!         let _ = pkt.data();
//!     }
//! }
//!
//! // Client: connect and send
//! if let Some(conn) = node.connect(libcsp::Priority::Norm, 2, 10, 1000, 0) {
//!     let mut pkt = Packet::get(32).expect("no packet buffers");
//!     pkt.write(b"hello").unwrap();
//!     let _ = conn.send_discard(pkt, 100);
//! }
//! ```
//!
//! ## Feature flags
//!
//! | Feature | Default | Description |
//! |---------|---------|-------------|
//! | `std` | ✓ | Enable `std::error::Error` impl and standard library helpers |
//! | `rdp` | ✓ | Reliable Datagram Protocol transport |
//! | `crc32` | ✓ | CRC32 packet integrity |
//! | `hmac` | ✓ | HMAC-SHA1 authentication |
//! | `xtea` | ✓ | XTEA encryption |
//! | `qos` | ✓ | Quality of Service (priority queues) |
//! | `promisc` | ✓ | Promiscuous mode |
//! | `dedup` | ✓ | Packet deduplication |
//! | `cidr-rtable` | – | CIDR routing table (instead of static) |
//! | `socketcan` | – | Linux SocketCAN driver |
//! | `zmq` | – | ZMQ hub interface |
//! | `usart-linux` | – | Linux USART/KISS driver |
//! | `usart-windows` | – | Windows USART driver |
//! | `debug` | – | Enable CSP debug output |
//! | `debug-timestamp` | – | Add timestamps to debug output |
//!
//! ## `no_std` support
//!
//! Disable the `std` feature to build for `no_std` targets.  The `alloc` crate
//! is still required (for `CString` in [`CspConfig`]).  All other modules use
//! only `core`.
//!
//! ```toml
//! [dependencies]
//! libcsp = { version = "1.6", default-features = false, features = ["rdp", "crc32"] }
//! ```

// ── no_std configuration ─────────────────────────────────────────────────────
#![cfg_attr(not(feature = "std"), no_std)]

// We need `alloc` for CString in init.rs on no_std targets.
extern crate alloc;

// ── Modules ───────────────────────────────────────────────────────────────────

/// Raw, unsafe FFI bindings generated by bindgen.
///
/// Prefer the safe wrappers in the crate root.  The raw API is available here
/// for advanced use cases (e.g. custom interfaces, direct `csp_rtable_*` calls).
pub mod sys;

mod error;
mod init;
mod packet;
mod connection;
mod socket;
pub mod route;
pub mod promisc;
pub mod interface;
pub mod service;
pub mod arch;

// ── Public re-exports ─────────────────────────────────────────────────────────

pub use error::CspError;
pub use init::{CspConfig, CspNode};
pub use packet::Packet;
pub use connection::Connection;
pub use socket::Socket;
pub use interface::{CspInterface, InterfaceHandle};
pub use service::{Ident, IfStats, Dispatcher};
pub use arch::CspArch;

#[macro_use]
pub mod arch_macro {
    pub use crate::export_arch;
}

/// Convenience `Result` type with [`CspError`] as the error variant.
pub type Result<T> = core::result::Result<T, CspError>;

// ── Priority enum ─────────────────────────────────────────────────────────────

/// CSP message priority.
///
/// Matches `csp_prio_t` in `csp_types.h`.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Priority {
    /// Critical priority (0 — highest).
    Critical = 0,
    /// High priority (1).
    High     = 1,
    /// Normal priority (2 — default).
    Norm     = 2,
    /// Low priority (3 — lowest).
    Low      = 3,
}

// ── Socket / connection option constants ──────────────────────────────────────

/// Socket options bitmask (`CSP_SO_*`).
///
/// These map directly to the `CSP_SO_*` constants in `csp_types.h` and can be
/// combined with `|`.
pub mod socket_opts {
    /// No options.
    pub const NONE: u32           = 0x0000;
    /// Require RDP.
    pub const RDP_REQ: u32        = 0x0001;
    /// Prohibit RDP.
    pub const RDP_PROHIB: u32     = 0x0002;
    /// Require HMAC.
    pub const HMAC_REQ: u32       = 0x0004;
    /// Prohibit HMAC.
    pub const HMAC_PROHIB: u32    = 0x0008;
    /// Require XTEA.
    pub const XTEA_REQ: u32       = 0x0010;
    /// Prohibit XTEA.
    pub const XTEA_PROHIB: u32    = 0x0020;
    /// Require CRC32.
    pub const CRC32_REQ: u32      = 0x0040;
    /// Prohibit CRC32.
    pub const CRC32_PROHIB: u32   = 0x0080;
    /// Enable connection-less mode.
    pub const CONN_LESS: u32      = 0x0100;
}

/// Connection options aliases (`CSP_O_*`).
///
/// Same numeric values as [`socket_opts`] — provided as a separate module
/// for clarity at call sites.
pub mod conn_opts {
    pub use super::socket_opts::{
        NONE, RDP_REQ as RDP, RDP_PROHIB as NORDP,
        HMAC_REQ as HMAC, HMAC_PROHIB as NOHMAC,
        XTEA_REQ as XTEA, XTEA_PROHIB as NOXTEA,
        CRC32_REQ as CRC32, CRC32_PROHIB as NOCRC32,
    };
}

/// Broadcast address (all nodes).
pub const BROADCAST_ADDR: u8 = 31; // CSP_ID_HOST_MAX = (1 << 5) - 1

/// Accept packets on any port (use with [`Socket::bind`]).
pub const ANY_PORT: u8 = 255; // CSP_ANY

/// Infinite timeout (block until event occurs).
pub const MAX_TIMEOUT: u32 = 0xFFFF_FFFF;

// ── Port enum ─────────────────────────────────────────────────────────────────

/// CSP port numbers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Port {
    /// CSP Management Protocol (0).
    Cmp,
    /// Ping / echo (1).
    Ping,
    /// Process list (2).
    Ps,
    /// Free memory query (3).
    MemFree,
    /// Reboot / shutdown (4).
    Reboot,
    /// Free buffer count (5).
    BufFree,
    /// Uptime query (6).
    Uptime,
    /// Accept packets on any port (255).
    Any,
    /// Custom user-defined port.
    Custom(u8),
}

impl From<u8> for Port {
    fn from(p: u8) -> Self {
        match p {
            0 => Port::Cmp,
            1 => Port::Ping,
            2 => Port::Ps,
            3 => Port::MemFree,
            4 => Port::Reboot,
            5 => Port::BufFree,
            6 => Port::Uptime,
            255 => Port::Any,
            p => Port::Custom(p),
        }
    }
}

impl From<Port> for u8 {
    fn from(p: Port) -> u8 {
        match p {
            Port::Cmp => 0,
            Port::Ping => 1,
            Port::Ps => 2,
            Port::MemFree => 3,
            Port::Reboot => 4,
            Port::BufFree => 5,
            Port::Uptime => 6,
            Port::Any => 255,
            Port::Custom(p) => p,
        }
    }
}

impl Port {
    /// Return true if this is a reserved libcsp service port (0-6).
    pub fn is_service_port(&self) -> bool {
        let p: u8 = (*self).into();
        p <= 6
    }
}

// ── Standard ports ────────────────────────────────────────────────────────────

/// Reserved CSP service port numbers (`csp_service_port_t`).
pub mod ports {
    /// CSP Management Protocol.
    pub const CMP:     u8 = 0;
    /// Ping / echo.
    pub const PING:    u8 = 1;
    /// Process list.
    pub const PS:      u8 = 2;
    /// Free memory query.
    pub const MEMFREE: u8 = 3;
    /// Reboot / shutdown.
    pub const REBOOT:  u8 = 4;
    /// Free buffer count.
    pub const BUF_FREE: u8 = 5;
    /// Uptime query.
    pub const UPTIME:  u8 = 6;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_port_mapping() {
        assert_eq!(u8::from(Port::Cmp), 0);
        assert_eq!(u8::from(Port::Ping), 1);
        assert_eq!(u8::from(Port::Any), 255);
        assert_eq!(u8::from(Port::Custom(10)), 10);
        
        assert_eq!(Port::from(0), Port::Cmp);
        assert_eq!(Port::from(1), Port::Ping);
        assert_eq!(Port::from(255), Port::Any);
        assert_eq!(Port::from(10), Port::Custom(10));
    }
}
