/*
Cubesat Space Protocol - A small network-layer protocol designed for Cubesats
Copyright (C) 2012 GomSpace ApS (http://www.gomspace.com)
Copyright (C) 2012 AAUSAT3 Project (http://aausat3.space.aau.dk)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
*/

//! # libcsp — Safe Rust bindings for libcsp v2.1
//!
//! Idiomatic, zero-unsafe Rust wrappers around the
//! [Cubesat Space Protocol](https://github.com/libcsp/libcsp) C library.
//!
//! The default configuration selects CSP **wire format version 1** (5-bit
//! host address, 4-byte header). Override via [`CspConfig::version`] if you
//! need v2 framing.
//!
//! ## Important Limitation
//!
//! **Only one [`CspNode`] can exist at a time** per process, because libcsp
//! holds its state in globals. [`CspConfig::init()`] returns
//! [`CspError::AlreadyInitialized`] on the second call. Clone the `CspNode`
//! to share it across threads.
//!
//! ## Quick start
//!
//! ```no_run
//! use libcsp::{CspConfig, Packet, Socket};
//!
//! let node = CspConfig::new()
//!     .address(1)
//!     .hostname("my-sat")
//!     .init()
//!     .expect("csp_init failed");
//!
//! node.route_start_task(0, 0).expect("router task failed");
//!
//! let mut sock = Socket::new(0);
//! sock.bind(10).unwrap();
//! sock.listen(5).unwrap();
//!
//! if let Some(conn) = sock.accept(1000) {
//!     while let Some(pkt) = conn.read(100) {
//!         let _ = pkt.data();
//!     }
//! }
//!
//! if let Some(conn) = node.connect(libcsp::Priority::Norm, 2, 10, 1000, 0) {
//!     let mut pkt = Packet::get(32).expect("no packet buffers");
//!     pkt.write(b"hello").unwrap();
//!     conn.send(pkt);
//! }
//! ```
//!
//! ## Buffer sizing
//!
//! Buffer count, buffer size and connection limits are compile-time constants
//! injected by the build script. Override them at build time:
//!
//! ```shell
//! LIBCSP_BUFFER_SIZE=512 LIBCSP_BUFFER_COUNT=20 cargo build
//! ```
//!
//! Read the resolved values back via the [`consts`] module.
//!
//! ## Feature flags
//!
//! | Feature | Default | Description |
//! |---------|---------|-------------|
//! | `std` | ✓ | Enable `std::error::Error` impl and standard library helpers |
//! | `rdp` | ✓ | Reliable Datagram Protocol transport |
//! | `hmac` | ✓ | HMAC-SHA1 authentication |
//! | `promisc` | ✓ | Promiscuous mode |
//! | `dedup` | ✓ | Packet deduplication (runtime toggle: [`init::DedupMode`]) |
//! | `socketcan` | – | Linux SocketCAN driver |
//! | `zmq` | – | ZMQ hub interface |
//! | `usart-linux` | – | Linux USART/KISS driver |
//! | `debug` | – | Enable CSP debug output |
//! | `zmq-v1-fixup` | – | Swap to little-endian CSP v1 headers over ZMQ |
//! | `buffer-zero-clear` | – | Zero freed buffers on release |
//!
//! ## `no_std` support
//!
//! Disable the `std` feature. `alloc` is still required (for `CString` in
//! [`CspConfig`]).
//!
//! ```toml
//! [dependencies]
//! libcsp = { version = "2.1", default-features = false, features = ["rdp"] }
//! ```

// ── no_std configuration ─────────────────────────────────────────────────────
#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

// ── Modules ───────────────────────────────────────────────────────────────────

/// Raw, unsafe FFI bindings generated by bindgen.
pub mod sys;

pub mod arch;
pub mod can;
mod connection;
pub mod consts;
mod error;
pub mod init;
pub mod interface;
mod packet;
pub mod promisc;
pub mod route;
pub mod service;
mod socket;

#[cfg(feature = "debug")]
pub mod debug;

// When 'external-arch' is enabled, libcsp expects the user to provide the
// architecture-specific implementation. To allow standard host tests and
// examples to run with this feature enabled (e.g. via --all-features),
// we provide a default stub implementation for host platforms.
//
// Gated additionally on `host-default-arch` (default-on) so that downstream
// crates wanting to provide their own arch on a host target can opt out via
// `default-features = false` — see `examples/custom_arch_external/`.
#[cfg(all(
    feature = "std",
    feature = "external-arch",
    feature = "host-default-arch",
    any(target_os = "linux", target_os = "macos")
))]
mod arch_default_export {
    use crate::arch::test_arch::{TestArch, ARCH};
    crate::export_arch!(TestArch, ARCH);
}

// ── Public re-exports ─────────────────────────────────────────────────────────

pub use arch::CspArch;
pub use can::{CanDriver, CanInterfaceHandle};
pub use connection::Connection;
pub use error::CspError;
pub use init::{CspConfig, CspNode, DedupMode};
pub use interface::{CspInterface, InterfaceHandle};
pub use packet::Packet;
pub use service::{Dispatcher, Ident, IfStats};
pub use socket::Socket;

#[macro_use]
pub mod arch_macro {
    pub use crate::export_arch;
}

/// Convenience `Result` type with [`CspError`] as the error variant.
pub type Result<T> = core::result::Result<T, CspError>;

// ── Priority enum ─────────────────────────────────────────────────────────────

/// CSP message priority (matches `csp_prio_t`).
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Priority {
    /// Critical priority (0 — highest).
    Critical = sys::csp_prio_t_CSP_PRIO_CRITICAL as u8,
    /// High priority (1).
    High = sys::csp_prio_t_CSP_PRIO_HIGH as u8,
    /// Normal priority (2 — default).
    Norm = sys::csp_prio_t_CSP_PRIO_NORM as u8,
    /// Low priority (3 — lowest).
    Low = sys::csp_prio_t_CSP_PRIO_LOW as u8,
}

// ── Socket / connection option constants ──────────────────────────────────────

/// Socket options bitmask (`CSP_SO_*`).
pub mod socket_opts {
    use crate::sys;

    pub const NONE: u32 = sys::CSP_SO_NONE;
    pub const RDP_REQ: u32 = sys::CSP_SO_RDPREQ;
    pub const RDP_PROHIB: u32 = sys::CSP_SO_RDPPROHIB;
    pub const HMAC_REQ: u32 = sys::CSP_SO_HMACREQ;
    pub const HMAC_PROHIB: u32 = sys::CSP_SO_HMACPROHIB;
    pub const CRC32_REQ: u32 = sys::CSP_SO_CRC32REQ;
    pub const CRC32_PROHIB: u32 = sys::CSP_SO_CRC32PROHIB;
    pub const CONN_LESS: u32 = sys::CSP_SO_CONN_LESS;
}

/// Connection options aliases (`CSP_O_*`).
pub mod conn_opts {
    pub use super::socket_opts::{
        CRC32_PROHIB as NOCRC32, CRC32_REQ as CRC32, HMAC_PROHIB as NOHMAC, HMAC_REQ as HMAC, NONE,
        RDP_PROHIB as NORDP, RDP_REQ as RDP,
    };
}

/// Broadcast address for CSP wire version 1 (`2^5 - 1 = 31`).
///
/// For wire version 2 the broadcast address is `2^14 - 1`. Call
/// `sys::csp_id_get_max_nodeid()` after [`CspConfig::init()`] for a
/// version-correct value at runtime.
pub const BROADCAST_ADDR: u16 = 31;

/// Accept packets on any port (use with [`Socket::bind`]).
pub const ANY_PORT: u8 = sys::CSP_ANY as u8;

/// Infinite timeout (block until event occurs).
pub const MAX_TIMEOUT: u32 = u32::MAX;

// ── Port enum ─────────────────────────────────────────────────────────────────

/// CSP port numbers.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Port {
    /// CSP Management Protocol (0).
    Cmp = 0,
    /// Ping / echo (1).
    Ping = 1,
    /// Process list (2).
    Ps = 2,
    /// Free memory query (3).
    MemFree = 3,
    /// Reboot / shutdown (4).
    Reboot = 4,
    /// Free buffer count (5).
    BufFree = 5,
    /// Uptime query (6).
    Uptime = 6,
    /// Accept packets on any port (255).
    Any = 255,
    /// Custom user-defined port.
    Custom(u8) = 254,
}

impl From<u8> for Port {
    fn from(p: u8) -> Self {
        match p {
            0 => Port::Cmp,
            1 => Port::Ping,
            2 => Port::Ps,
            3 => Port::MemFree,
            4 => Port::Reboot,
            5 => Port::BufFree,
            6 => Port::Uptime,
            255 => Port::Any,
            p => Port::Custom(p),
        }
    }
}

impl From<Port> for u8 {
    fn from(p: Port) -> u8 {
        match p {
            Port::Cmp => 0,
            Port::Ping => 1,
            Port::Ps => 2,
            Port::MemFree => 3,
            Port::Reboot => 4,
            Port::BufFree => 5,
            Port::Uptime => 6,
            Port::Any => 255,
            Port::Custom(p) => p,
        }
    }
}

impl Port {
    /// Return true if this is a reserved libcsp service port (0-6).
    pub fn is_service_port(&self) -> bool {
        let p: u8 = (*self).into();
        p <= 6
    }
}

// ── Standard ports ────────────────────────────────────────────────────────────

/// Reserved CSP service port numbers.
pub mod ports {
    pub const CMP: u8 = 0;
    pub const PING: u8 = 1;
    pub const PS: u8 = 2;
    pub const MEMFREE: u8 = 3;
    pub const REBOOT: u8 = 4;
    pub const BUF_FREE: u8 = 5;
    pub const UPTIME: u8 = 6;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_port_mapping() {
        assert_eq!(u8::from(Port::Cmp), 0);
        assert_eq!(u8::from(Port::Ping), 1);
        assert_eq!(u8::from(Port::Any), 255);
        assert_eq!(u8::from(Port::Custom(10)), 10);

        assert_eq!(Port::from(0), Port::Cmp);
        assert_eq!(Port::from(1), Port::Ping);
        assert_eq!(Port::from(255), Port::Any);
        assert_eq!(Port::from(10), Port::Custom(10));
    }
}

// ── Test helpers ──────────────────────────────────────────────────────────────

#[cfg(test)]
pub(crate) mod test_helpers {
    use crate::CspConfig;
    use std::sync::Mutex;

    /// Global test lock that serialises CSP initialisation. libcsp keeps its
    /// state in globals, so tests must not run in parallel.
    pub static TEST_LOCK: Mutex<()> = Mutex::new(());

    /// Run a closure with an initialised CSP stack; the stack is torn down
    /// when the closure returns.
    pub fn with_csp_node<F: FnOnce(&crate::CspNode)>(f: F) {
        // Recover from a poisoned lock so one panicking test doesn't
        // cascade into the whole suite. Individual tests are expected to
        // run single-threaded (cargo test --test-threads=1) since libcsp
        // keeps global state.
        let _guard = TEST_LOCK
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());

        let node = CspConfig::new()
            .address(1)
            .init()
            .expect("failed to init CSP for tests");

        f(&node);
    }
}
